# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LaFarge' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LaFarge

  target 'LaFarge-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-icons', :path => '../node_modules/react-native-icons'

  end

  target 'LaFargeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LaFarge-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LaFarge-tvOS

  target 'LaFarge-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'